name: Update Distribution

concurrency:
  group: dist-${{ github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: write

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  update_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - uses: dtolnay/rust-toolchain@stable
      - run: chmod +x ./dist.sh && ./dist.sh
        shell: bash
      - name: Push Updated Dist
        run: |
          git diff --quiet && exit 0
          git pull
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "update macos dist"
          git push origin HEAD:${{ github.ref_name }}
        shell: bash

  update_windows:
    needs: update_macos
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - uses: dtolnay/rust-toolchain@stable
      - run: ./dist.sh
        shell: bash
      - name: Push Updated Dist
        run: |
          git diff --quiet && exit 0
          git pull
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "update windows dist"
          git push origin HEAD:${{ github.ref_name }}
        shell: bash

  update_ubuntu:
    needs: update_windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - uses: dtolnay/rust-toolchain@stable
      - run: chmod +x ./dist.sh && ./dist.sh
        shell: bash
      - name: Push Updated Dist
        run: |
          git diff --quiet && exit 0
          git pull
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "update linux dist"
          git push origin HEAD:${{ github.ref_name }}
        shell: bash
